### ISSUE TITLE
Headline Hackathon

### ISSUE THREAD

**Issue by davonjagah** [ChoiceCoin/HerTechChoice#34]
Blockchain technologies are a game changer for businesses of all sizes, It allows for quick and secure purchases without the need of traditional payment processors and their Complexities.

The Algorand Blockchain prides itself as the world's most decentralized, scalable, and secure blockchain infrastructure. It has a low fee of 0.0005$ and over 26,000,000 Addresses created making it a good Infrastructure for a Businesses to Thrive.

**REQUIREMENTS**
This Hackathon aims to empower developers of all skill levels. 

For this Hackathon which is sponsored by HEADLINE and CHOICE COIN DAO, You are required to build applications for the Algorand System across all Sphere of Developments.  

We invite the Use of Choice Coin, Headline Tools or other Algorand Technologies. Any contribution to the Ecosystem would be a Valid one.

**Rules**

All files must be made in one folder, with the folder name `username_hack` and all folders must be added to the [HeadlineHackathon](https://github.com/ChoiceCoin/HerTechChoice/tree/main/HeadlineHackathon) Folder. 

Make a Pull Request to [https://github.com/ChoiceCoin/HerTechChoice](https://github.com/ChoiceCoin/HerTechChoice)

Comment a link to your PR with Your Algorand Wallet Address, Your Email Address and your Twitter Account(optional) under this [Issue](https://github.com/ChoiceCoin/HerTechChoice/issues/34) .

Hackathon participants will have 3 days to explore, experiment, and build.

The hackathon runs from June 10th to June 13th, 2022.

**PRIZES:**

1st POSITION
200 $ALGO
200,000 $CHOICE

2nd POSITION
150 $ALGO
150,000 $CHOICE

3rd POSITION
150 $ALGO
100,000 $CHOICE

Other Participants Share a Pool of 550,000 $CHOICE.

Good Luck Everyone.

**Comment by Dreamf1re** [comment]
Pull Request: https://github.com/ChoiceCoin/HerTechChoice/pull/37
Algorand Wallet Address: 7L6ADWKLS4MQK6PRHZUJYEPD6BQHF7L2IL7LHDKOSJTXSBHAK544Z4ACNI
Email Address: vrandrigroft@protonmail.com

**Comment by BisiShitta** [comment]
Pull Request: https://github.com/ChoiceCoin/HerTechChoice/pull/38
Algorand Wallet Address:  ﻿OVVPRTQ7I3QTNUIZWGWY7452WMZ4SA3KFT2OB73NRUSGJS3H2F2BW4NBZE
Email Address: shitta19@gmail.com
Twitter: darkgloww

**Comment by Apekeade** [comment]
pull request: https://github.com/ChoiceCoin/HerTechChoice/pull/39.
Algorand Wallet Address: XIBYN63S62FUMZEUKVLSIGAEM2SE5NVPJRJTXOYVHQV5U3WHSSCGQFTASU.
Email Address:  okate369@gmail.com.

**Comment by davonjagah** [comment]
Thanks for Your submissions. They would be Evaluated and winners announced shortly

**Comment by davonjagah** [comment]
The Submissions have now been Evaluated. And the winners are as follows:


1st POSITION @BisiShitta 
200 $ALGO
200,000 $CHOICE

2nd POSITION @Dreamf1re 
150 $ALGO
150,000 $CHOICE

3rd POSITION @Apekeade 
150 $ALGO
100,000 $CHOICE

Rewards would be Sent Immediately. Keep Building and Building Something Great
